### ISSUE TITLE
After SASL Authentication succeeded, Getting error

### ISSUE THREAD

**Issue by zoom2manoj** [processone/xmpp-websocket-client#1]
`
228.84 _connect_cb was called
228.84 <stream:features><mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><mechanism>ANONYMOUS</mechanism><mechanism>PLAIN</mechanism><mechanism>X-OAUTH2</mechanism></mechanisms></stream:features>

228.84 <auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='PLAIN'>RGFuaWVsQGNyYXp5Y2hhdGJvdC5jb20ARGFuaWVsADFAMzQ1Njdw</auth>

228.92 <success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'/>

228.92 SASL authentication succeeded.

229.00 <stream:error><not-well-formed xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmlns='urn:ietf:params:xml:ns:xmpp-streams' xml:lang='en'>XML or text declaration not at start of entity</text></stream:error>
229.00 <parsererror style='display: block; white-space: pre; border: 2px solid #c77; padding: 0 1em 0 1em; margin: 1em; background-color: #fdd; color: black'><h3>This page contains the following errors:</h3><div style='font-family:monospace;font-size:12px'>error on line 1 at column 43: Opening and ending tag mismatch: body line 0 and stream:stream </div><h3>Below is a rendering of the page up to the first error.</h3></parsererror>

229.07 websocket closed
229.07 _doDisconnect was called
229.08 Disconnected
`

**Comment by zinid** [comment]
I just close this junk.

**Comment by zoom2manoj** [comment]
Kindly suggest me about this issue, still, I'm getting the same issue as below:

36.49 <stream:error><not-well-formed xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmlns='urn:ietf:params:xml:ns:xmpp-streams' xml:lang='en'>XML or text declaration not at start of entity</text></stream:error>
36.49 <parsererror style='display: block; white-space: pre; border: 2px solid #c77; padding: 0 1em 0 1em; margin: 1em; background-color: #fdd; color: black'><h3>This page contains the following errors:</h3><div style='font-family:monospace;font-size:12px'>error on line 1 at column 43: Opening and ending tag mismatch: body line 0 and stream:stream </div><h3>Below is a rendering of the page up to the first error.</h3></parsererror>

**Comment by zoom2manoj** [comment]
I got message from ejabberd team as follow:

Hello,

This was just problem with that client, it was using old websocket protocol version, that was available before xmpp over websocket was standarized, i updated that client to use new protocol, it should work now.

Can we talk if possible?

**Comment by prefiks** [comment]
This client was updated today, and should work now.

**Comment by zoom2manoj** [comment]
Thanks for reply Pawel, 
I tried with updated repo code but getting one issue as follow:

Uncaught TypeError: Cannot read property '_rebind' of undefined
    at rebindOrConnect (main.js:101)
    at HTMLInputElement.<anonymous> (main.js:121)
    at HTMLInputElement.dispatch (jquery.js:3)
    at HTMLInputElement.i (jquery.js:3)

**Comment by prefiks** [comment]
Oups, forgot to commit new file, please update

**Comment by zoom2manoj** [comment]
Now working with updated ejabberd repo code.
Thank you very much Pawel for your kind support
